In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
if torch.cuda.is_available():
    print("✅ GPU is available:", torch.cuda.get_device_name(0))
else:
    print("❌ No GPU detected, running on CPU.")

✅ GPU is available: NVIDIA GeForce RTX 4060 Laptop GPU

In [5]:
# load data

df = pd.read_pickle("/home/trapfishscott/Cambridge24.25/D200_ML_econ/ProblemSets/Project/data/LSTM_ready_df.pkl")

In [6]:
df

,IndividualID_x,TripStart,TripEnd,NumTrips,TripDisExSW,TripPurpose_B01ID,TWSMonth,TravelYear,TravelWeekDay_B01ID
0,2.017000e+09,0.0,0.0,0,0.0,0.0,1.0,2017.0,0.0
1,2.017000e+09,600.0,620.0,2,4.0,6.0,1.0,2017.0,1.0
2,2.017000e+09,690.0,710.0,2,4.0,6.0,1.0,2017.0,1.0
3,2.017000e+09,0.0,0.0,0,0.0,0.0,1.0,2017.0,2.0
4,2.017000e+09,0.0,0.0,0,0.0,0.0,1.0,2017.0,3.0
...,...,...,...,...,...,...,...,...,...
126605,2.017017e+09,645.0,660.0,2,2.0,5.0,1.0,2018.0,5.0
126606,2.017017e+09,660.0,680.0,2,2.0,13.0,1.0,2018.0,6.0
126607,2.017017e+09,840.0,860.0,2,2.0,13.0,1.0,2018.0,6.0
126608,2.017017e+09,0.0,0.0,0,0.0,0.0,1.0,2018.0,7.0
126609,2.017017e+09,0.0,0.0,0,0.0,0.0,1.0,2018.0,8.0